/**
 * server.js
 * 
 * Production server entry point for Next.js standalone deployment on cPanel.
 * This file is automatically generated/copied by scripts/copy-assets.js
 * 
 * Usage: NODE_ENV=production node server.js
 * 
 * For cPanel deployment: Use the server.js in the deploy/ folder
 */

const { createServer } = require('http');
const { parse } = require('url');
const { existsSync } = require('fs');
const { join, dirname } = require('path');
const next = require('next');

const dev = process.env.NODE_ENV !== 'production';
const hostname = 'localhost';
const port = parseInt(process.env.PORT || '3000', 10);

// Determine the correct directory for Next.js
// For standalone: check if .next/standalone exists, otherwise use project root
let nextDir = __dirname;

// Check if we're in standalone mode (deployed to cPanel)
const standaloneDir = join(__dirname, '.next', 'standalone');
if (existsSync(standaloneDir)) {
  // We're in standalone mode - server.js is in .next/standalone/
  nextDir = dirname(dirname(join(__dirname, '.next'))); // Go up to project root
} else if (existsSync(join(__dirname, 'next.config.js')) || existsSync(join(__dirname, 'next.config.ts'))) {
  // We're in project root with standard Next.js setup
  nextDir = __dirname;
} else {
  // Fallback to current directory
  nextDir = __dirname;
}

console.log('📍 Next.js directory:', nextDir);
console.log('📍 Running from:', __dirname);

// Validate required environment variables
if (!dev) {
  const requiredVars = ['NEXT_PUBLIC_SUPABASE_URL', 'NEXT_PUBLIC_SUPABASE_ANON_KEY'];
  const missing = requiredVars.filter(v => !process.env[v]);
  
  console.log('📋 Environment Check:');
  console.log('  NODE_ENV:', process.env.NODE_ENV || '(not set)');
  console.log('  PORT:', process.env.PORT || '(not set, using default 3000)');
  console.log('  NEXT_PUBLIC_SUPABASE_URL:', process.env.NEXT_PUBLIC_SUPABASE_URL ? '✅ Set' : '❌ MISSING');
  console.log('  NEXT_PUBLIC_SUPABASE_ANON_KEY:', process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY ? '✅ Set (length: ' + process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY.length + ')' : '❌ MISSING');
  console.log('  RESEND_API_KEY:', process.env.RESEND_API_KEY ? '✅ Set' : '⚠️ Not set');
  console.log('  NEXT_PUBLIC_APP_URL:', process.env.NEXT_PUBLIC_APP_URL || '⚠️ Not set');
  console.log('  __dirname:', __dirname);
  console.log('  process.cwd():', process.cwd());
  console.log('');
  
  if (missing.length > 0) {
    console.warn(`⚠️  Warning: Missing environment variables: ${missing.join(', ')}`);
    console.warn('Some features may not work correctly.\n');
  }
}

const app = next({ dev, hostname, port, dir: nextDir });
const handle = app.getRequestHandler();

// Graceful shutdown handlers
const shutdown = () => {
  console.log('🛑 Shutting down gracefully...');
  server.close(() => {
    console.log('✅ HTTP server closed');
    process.exit(0);
  });
  
  // Force close after 10 seconds
  setTimeout(() => {
    console.error('⚠️  Forced shutdown after timeout');
    process.exit(1);
  }, 10000);
};

process.on('SIGTERM', shutdown);
process.on('SIGINT', shutdown);

app.prepare().then(() => {
  const server = createServer(async (req, res) => {
    try {
      const parsedUrl = parse(req.url, true);
      
      // Add security headers
      res.setHeader('X-Content-Type-Options', 'nosniff');
      res.setHeader('X-Frame-Options', 'SAMEORIGIN');
      res.setHeader('X-XSS-Protection', '1; mode=block');
      
      // Remove powered by header for security
      res.removeHeader('X-Powered-By');
      
      await handle(req, res, parsedUrl);
    } catch (err) {
      console.error('❌ Error occurred handling', req.url, err);
      res.statusCode = 500;
      res.end('Internal Server Error');
    }
  });

  // Error handling
  server.on('error', (err) => {
    if (err.code === 'EADDRINUSE') {
      console.error(`❌ Port ${port} is already in use.`);
      console.error('Please check if another instance is running or use a different port:');
      console.error(`  PORT=3001 node server.js`);
      process.exit(1);
    } else {
      console.error('❌ Server error:', err);
      throw err;
    }
  });

  server.listen(port, (err) => {
    if (err) throw err;
    
    console.log('\n🚀 BNS Application Started');
    console.log('============================');
    console.log(`> Environment: ${dev ? 'development' : 'production'}`);
    console.log(`> Server: http://${hostname}:${port}`);
    console.log(`> PID: ${process.pid}`);
    console.log('============================\n');
    
    // Log startup info
    console.log('📋 Environment Info:');
    console.log(`  - Node.js: ${process.version}`);
    console.log(`  - Platform: ${process.platform}`);
    console.log(`  - Memory: ${Math.round(process.memoryUsage().heapUsed / 1024 / 1024)}MB / ${Math.round(process.memoryUsage().heapTotal / 1024 / 1024)}MB`);
    console.log('');
  });
});
